export { default as Navbar } from './Navbar'
export { default as DesktopSidebar } from './DesktopSidebar'
export { default as Home } from './Home'
export { default as About } from './About'
export { default as Skills } from './Skills'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'